 name: houston
 channels:
   - conda-forge
 dependencies:
   - python=3.5
   - numpy
   - matplotlib
   - cartopy
   - jupyter
   - netcdf4
   - metpy
   - siphon
   - xarray
   - scipy
   - boto
   - basemap
   - basemap-data-hires
   - boto3

